from env import StudyEnvironment
print('=== EASY ===')
env = StudyEnvironment('easy')
env.reset()
r = env.step({'complete_task_id': 1})
print('step1:', r['reward'], 'done:', r['done'])
assert r['done'] == True
print('=== MEDIUM ===')
env = StudyEnvironment('medium')
env.reset()
r = env.step({'complete_task_id': 1})
print('step1:', r['reward'], 'done:', r['done'])
r = env.step({'complete_task_id': 2})
print('step2:', r['reward'], 'done:', r['done'])
assert r['done'] == True
print('=== HARD ===')
env = StudyEnvironment('hard')
env.reset()
r = env.step({'complete_task_id': 1})
print('step1:', r['reward'], 'done:', r['done'])
r = env.step({'complete_task_id': 2})
print('step2:', r['reward'], 'done:', r['done'])
r = env.step({'complete_task_id': 3})
print('step3:', r['reward'], 'done:', r['done'])
assert r['done'] == True
print('ALL 3 TASKS PASSED')
